### ISSUE TITLE
Slicer: Plugin not getting updated through nightly build

### ISSUE THREAD

**Issue by SachidanandAlle** [NVIDIA/ai-assisted-annotation-client#59]
The last build was on 30th Jan, 2020.  Any changes after that are not getting pushed to plugin repository through nightly build.  However build was successful on CDash

http://slicer.cdash.org/index.php?project=SlicerPreview

However some error for Slicer4 version: http://slicer.cdash.org/viewBuildError.php?buildid=1839709

**Comment by lassoan** [comment]
The plugin is successfully built and packaged for Slicer Preview Releases every night (latest hash is f0cfc5e - Feb 26, 2020):
http://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=Nvidia

The Slicer plugin is not compatible with latest stable (Slicer-4.10.2) - it would have been too much work to develop and maintain it because of lots of differences due to Python 2/3 and Slicer API changes.

**Comment by lassoan** [comment]
I have tested the latest nightly and it had lots of issues.

Serious problems:
- default segmentation server address was missing, so by default the effect reports an error and the users cannot do anything with it
- Auto-segmentation and DExtr3D method fails to upload the data to the server (maybe because we use a v1 server, but we could not set up a v2 server), the same server works perfectly with the client version before 2020-02-21; I could not test DeepGrow as we don't have such models on our server; see log message at the bottom

Minor inconveniences (if you feel strongly about any of these then we can add options to the application settings to control these):
- a popup comes up after models are fetched (useful debug information but user workflow should not be disrupted with popups)
- filter of model names based on segment name is enabled by default (useful if there are many models, but if it's enabled by default then all the users see is that they cannot select anything, they don't know that the filtering should be turned off)
- the most successful (fastest, most robust) method - DExtr3D - is collapsed by default

Until these problems are fixed (either we upgrade the default segmentation server to a more recent version that is compatible with the latest client; or the client is made to be backward compatible), I've fixed the nightly git hash to use the last working version - 544261ee900647e89cf13f9ccd78b10b71f731ef.

File upload failure log:
```
Traceback (most recent call last):
  File "C:/Users/andra/AppData/Roaming/NA-MIC/Extensions-28794/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorNvidiaAIAALib/SegmentEditorEffect.py", line 358, in createAiaaSessionIfNotExists
    in_file, session_id = self.logic.createSession(inputVolume)
  File "C:/Users/andra/AppData/Roaming/NA-MIC/Extensions-28794/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorNvidiaAIAALib/SegmentEditorEffect.py", line 965, in createSession
    response = aiaaClient.create_session(in_file)
  File "C:\Users\andra\AppData\Roaming\NA-MIC\Extensions-28794\NvidiaAIAssistedAnnotation\lib\Slicer-4.11\qt-scripted-modules\NvidiaAIAAClientAPI\client_api.py", line 108, in create_session
    raise AIAAException(AIAAError.SERVER_ERROR, 'Status: {}; Response: {}'.format(status, response))
NvidiaAIAAClientAPI.client_api.AIAAException: (3, 'Status: 404; Response: b\'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\\n<title>404 Not Found</title>\\n<h1>Not Found</h1>\\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\\n\'')
```

**Comment by SachidanandAlle** [comment]
Due to security reasons, we have dropped clara v1 support.  (None of the models is available in NV docker for pull)

However as suggested above, lets support v1 in slicer plugin for backward compatibility until default public host for slicer gets an upgrade.

Both _Serious problems_ and _Minor inconveniences_ as reported above are taken care in this PR. Please review and approve if all is good.

https://github.com/NVIDIA/ai-assisted-annotation-client/pull/60

**Comment by lassoan** [comment]
I would like to update our server to v2 interface and upload DeepGrow models. Can you point me to documentation that describes the install process? I tried it a few months ago and I succeeded with installation of v1 server and models but I could not make v2 server work (or could not upload models, I don't remember exactly). Thank you!

**Comment by SachidanandAlle** [comment]
still no luck :(

![image](https://user-images.githubusercontent.com/7339051/75819019-cb429180-5d91-11ea-8e8f-744e48d13494.png)

**Comment by lassoan** [comment]
It works perfectly for me:
![image](https://user-images.githubusercontent.com/307929/75819222-3ecfa900-5d68-11ea-9689-9baba14dbde0.png)

What Slicer version and operating system do you use?

**Comment by SachidanandAlle** [comment]
Its on windows.. I am using 4.11.0 2020-01-09 version

**Comment by lassoan** [comment]
Extensions are only rebuilt every night for latest stable and latest preview releases.
Since this extension is not available for latest stable, you need to install latest Slicer Preview Release to get latest version of the extension.

**Comment by SachidanandAlle** [comment]
ah.. I didn't know about this binding.. I can see all good with latest version... verified all 3 actions. 
I guess good to for GTC :)

I will let you know once the docker version for v3 is public.  It should be sooner ( in couple of days ) and also this time, we will help you to setup basic v2/v3 models including deepgrow for default public server.
